/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Filters: typeof import('./src/components/layout/navbar/Filters.vue')['default']
    Main: typeof import('./src/components/layout/Main.vue')['default']
    Menu: typeof import('./src/components/layout/navbar/Menu.vue')['default']
    ModelCard: typeof import('./src/components/ModelCard.vue')['default']
    Navbar: typeof import('./src/components/layout/navbar/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeriesCard: typeof import('./src/components/SeriesCard.vue')['default']
  }
}
